version: "3.8"
services:
  rdb:
    image: postgres:12.0
    ports:
      - "5432:5432"
    volumes:
      - pgdatavolume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdatavolume: {}
